version: '3'

services:
  ovs-vswitchd:
    image: openvswitch/ovs:2.11.2_debian
    command: ovs-vswitchd
    container_name: ovs-vswitchd
    network_mode: host
    privileged: true
    volumes:
      - ./data:/data


