version: "3"

services:
  ovsdb-server:
    image: openvswitch/ovs:2.11.2_debian
    container_name: ovs
    cap_add:
     - SYS_NICE
    command: ovsdb-server
    networks:
      mynetwork:
        ipv4_address: 172.28.1.2
      mynetwork2:
        ipv4_address: 172.29.1.2
    volumes:
      - ovs-socket:/var/run/openvswitch
    restart: unless-stopped

  ovs-vswitchd:
    image: openvswitch/ovs:2.11.2_debian
    container_name: ovs-vswitchd
    command: ovs-vswitchd --pidfile --detach --no-chdir --log-file=/var/log/openvswitch/ovs-vswitchd.log
    network_mode: "service:ovsdb-server"
    volumes:
      - ovs-socket:/var/run/openvswitch
    privileged: true
    restart: unless-stopped
     
  ubuntu2:
    image: ubuntu
    container_name: ubuntu2
    command: tail -f /dev/null
    networks:
      mynetwork:
        ipv4_address: 172.28.1.3

  ubuntu3:
    image: ubuntu
    container_name: ubuntu3
    command: tail -f /dev/null
    networks:
      mynetwork2:
        ipv4_address: 172.29.1.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

  mynetwork2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  ovs-socket:
